/**
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Stat'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Stat'));
  } else {
    // Browser globals (root is window)
    if (!root.FnJs) {
      root.FnJs = {};
    }
    root.FnJs.Call = factory(root.FnJs.ApiClient, root.FnJs.Stat);
  }
}(this, function(ApiClient, Stat) {
  'use strict';




  /**
   * The Call model module.
   * @module model/Call
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Call</code>.
   * @alias module:model/Call
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>Call</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Call} obj Optional instance to populate.
   * @return {module:model/Call} The populated <code>Call</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], 'String');
      }
      if (data.hasOwnProperty('app_id')) {
        obj['app_id'] = ApiClient.convertToType(data['app_id'], 'String');
      }
      if (data.hasOwnProperty('fn_id')) {
        obj['fn_id'] = ApiClient.convertToType(data['fn_id'], 'String');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('started_at')) {
        obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Date');
      }
      if (data.hasOwnProperty('completed_at')) {
        obj['completed_at'] = ApiClient.convertToType(data['completed_at'], 'Date');
      }
      if (data.hasOwnProperty('stats')) {
        obj['stats'] = ApiClient.convertToType(data['stats'], [Stat]);
      }
    }
    return obj;
  }

  /**
   * Call ID.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Call execution status.
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * Call execution error, if status is 'error'.
   * @member {String} error
   */
  exports.prototype['error'] = undefined;
  /**
   * App ID of fn that executed this call.
   * @member {String} app_id
   */
  exports.prototype['app_id'] = undefined;
  /**
   * Fn ID of fn that executed this call.
   * @member {String} fn_id
   */
  exports.prototype['fn_id'] = undefined;
  /**
   * Time when call was submitted. Always in UTC.
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * Time when call started execution. Always in UTC.
   * @member {Date} started_at
   */
  exports.prototype['started_at'] = undefined;
  /**
   * Time when call completed, whether it was successul or failed. Always in UTC.
   * @member {Date} completed_at
   */
  exports.prototype['completed_at'] = undefined;
  /**
   * A histogram of stats for a call, each is a snapshot of a calls state at the timestamp.
   * @member {Array.<module:model/Stat>} stats
   */
  exports.prototype['stats'] = undefined;



  return exports;
}));


