/**
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FnJs) {
      root.FnJs = {};
    }
    root.FnJs.Fn = factory(root.FnJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Fn model module.
   * @module model/Fn
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Fn</code>.
   * @alias module:model/Fn
   * @class
   */
  var exports = function() {
    var _this = this;












  };

  /**
   * Constructs a <code>Fn</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fn} obj Optional instance to populate.
   * @return {module:model/Fn} The populated <code>Fn</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('app_id')) {
        obj['app_id'] = ApiClient.convertToType(data['app_id'], 'String');
      }
      if (data.hasOwnProperty('image')) {
        obj['image'] = ApiClient.convertToType(data['image'], 'String');
      }
      if (data.hasOwnProperty('memory')) {
        obj['memory'] = ApiClient.convertToType(data['memory'], 'Number');
      }
      if (data.hasOwnProperty('timeout')) {
        obj['timeout'] = ApiClient.convertToType(data['timeout'], 'Number');
      }
      if (data.hasOwnProperty('idle_timeout')) {
        obj['idle_timeout'] = ApiClient.convertToType(data['idle_timeout'], 'Number');
      }
      if (data.hasOwnProperty('config')) {
        obj['config'] = ApiClient.convertToType(data['config'], {'String': 'String'});
      }
      if (data.hasOwnProperty('annotations')) {
        obj['annotations'] = ApiClient.convertToType(data['annotations'], {'String': Object});
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
    }
    return obj;
  }

  /**
   * Unique identifier
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Unique name for this function.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * App ID.
   * @member {String} app_id
   */
  exports.prototype['app_id'] = undefined;
  /**
   * Full container image name, e.g. hub.docker.com/fnproject/yo or fnproject/yo (default registry: hub.docker.com)
   * @member {String} image
   */
  exports.prototype['image'] = undefined;
  /**
   * Maximum usable memory given to function (MiB).
   * @member {Number} memory
   */
  exports.prototype['memory'] = undefined;
  /**
   * Timeout for executions of a function. Value in Seconds.
   * @member {Number} timeout
   * @default 30
   */
  exports.prototype['timeout'] = 30;
  /**
   * Hot functions idle timeout before container termination. Value in Seconds.
   * @member {Number} idle_timeout
   * @default 30
   */
  exports.prototype['idle_timeout'] = 30;
  /**
   * Function configuration key values.
   * @member {Object.<String, String>} config
   */
  exports.prototype['config'] = undefined;
  /**
   * Func annotations - this is a map of annotations attached to this func, keys must not exceed 128 bytes and must consist of non-whitespace printable ascii characters, and the seralized representation of individual values must not exeed 512 bytes.
   * @member {Object.<String, Object>} annotations
   */
  exports.prototype['annotations'] = undefined;
  /**
   * Time when function was created. Always in UTC RFC3339.
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * Most recent time that function was updated. Always in UTC RFC3339.
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;



  return exports;
}));


