/**
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FnJs) {
      root.FnJs = {};
    }
    root.FnJs.Log = factory(root.FnJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Log model module.
   * @module model/Log
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Log</code>.
   * @alias module:model/Log
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Log</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Log} obj Optional instance to populate.
   * @return {module:model/Log} The populated <code>Log</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('call_id')) {
        obj['call_id'] = ApiClient.convertToType(data['call_id'], 'String');
      }
      if (data.hasOwnProperty('log')) {
        obj['log'] = ApiClient.convertToType(data['log'], 'String');
      }
    }
    return obj;
  }

  /**
   * Call UUID ID
   * @member {String} call_id
   */
  exports.prototype['call_id'] = undefined;
  /**
   * @member {String} log
   */
  exports.prototype['log'] = undefined;



  return exports;
}));


