/**
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/StatMetrics'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./StatMetrics'));
  } else {
    // Browser globals (root is window)
    if (!root.FnJs) {
      root.FnJs = {};
    }
    root.FnJs.Stat = factory(root.FnJs.ApiClient, root.FnJs.StatMetrics);
  }
}(this, function(ApiClient, StatMetrics) {
  'use strict';




  /**
   * The Stat model module.
   * @module model/Stat
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Stat</code>.
   * @alias module:model/Stat
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Stat</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Stat} obj Optional instance to populate.
   * @return {module:model/Stat} The populated <code>Stat</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('timestamp')) {
        obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
      }
      if (data.hasOwnProperty('metrics')) {
        obj['metrics'] = StatMetrics.constructFromObject(data['metrics']);
      }
    }
    return obj;
  }

  /**
   * @member {Date} timestamp
   */
  exports.prototype['timestamp'] = undefined;
  /**
   * @member {module:model/StatMetrics} metrics
   */
  exports.prototype['metrics'] = undefined;



  return exports;
}));


