/**
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FnJs) {
      root.FnJs = {};
    }
    root.FnJs.StatMetrics = factory(root.FnJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StatMetrics model module.
   * @module model/StatMetrics
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>StatMetrics</code>.
   * @alias module:model/StatMetrics
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>StatMetrics</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StatMetrics} obj Optional instance to populate.
   * @return {module:model/StatMetrics} The populated <code>StatMetrics</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('net_rx')) {
        obj['net_rx'] = ApiClient.convertToType(data['net_rx'], 'Number');
      }
      if (data.hasOwnProperty('net_tx')) {
        obj['net_tx'] = ApiClient.convertToType(data['net_tx'], 'Number');
      }
      if (data.hasOwnProperty('mem_limit')) {
        obj['mem_limit'] = ApiClient.convertToType(data['mem_limit'], 'Number');
      }
      if (data.hasOwnProperty('mem_usage')) {
        obj['mem_usage'] = ApiClient.convertToType(data['mem_usage'], 'Number');
      }
      if (data.hasOwnProperty('disk_read')) {
        obj['disk_read'] = ApiClient.convertToType(data['disk_read'], 'Number');
      }
      if (data.hasOwnProperty('disk_write')) {
        obj['disk_write'] = ApiClient.convertToType(data['disk_write'], 'Number');
      }
      if (data.hasOwnProperty('cpu_user')) {
        obj['cpu_user'] = ApiClient.convertToType(data['cpu_user'], 'Number');
      }
      if (data.hasOwnProperty('cpu_total')) {
        obj['cpu_total'] = ApiClient.convertToType(data['cpu_total'], 'Number');
      }
      if (data.hasOwnProperty('cpu_kernel')) {
        obj['cpu_kernel'] = ApiClient.convertToType(data['cpu_kernel'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} net_rx
   */
  exports.prototype['net_rx'] = undefined;
  /**
   * @member {Number} net_tx
   */
  exports.prototype['net_tx'] = undefined;
  /**
   * @member {Number} mem_limit
   */
  exports.prototype['mem_limit'] = undefined;
  /**
   * @member {Number} mem_usage
   */
  exports.prototype['mem_usage'] = undefined;
  /**
   * @member {Number} disk_read
   */
  exports.prototype['disk_read'] = undefined;
  /**
   * @member {Number} disk_write
   */
  exports.prototype['disk_write'] = undefined;
  /**
   * @member {Number} cpu_user
   */
  exports.prototype['cpu_user'] = undefined;
  /**
   * @member {Number} cpu_total
   */
  exports.prototype['cpu_total'] = undefined;
  /**
   * @member {Number} cpu_kernel
   */
  exports.prototype['cpu_kernel'] = undefined;



  return exports;
}));


