/**
 * fn
 * The open source serverless platform.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FnJs) {
      root.FnJs = {};
    }
    root.FnJs.Trigger = factory(root.FnJs.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Trigger model module.
   * @module model/Trigger
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>Trigger</code>.
   * @alias module:model/Trigger
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>Trigger</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Trigger} obj Optional instance to populate.
   * @return {module:model/Trigger} The populated <code>Trigger</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('source')) {
        obj['source'] = ApiClient.convertToType(data['source'], 'String');
      }
      if (data.hasOwnProperty('fn_id')) {
        obj['fn_id'] = ApiClient.convertToType(data['fn_id'], 'String');
      }
      if (data.hasOwnProperty('app_id')) {
        obj['app_id'] = ApiClient.convertToType(data['app_id'], 'String');
      }
      if (data.hasOwnProperty('annotations')) {
        obj['annotations'] = ApiClient.convertToType(data['annotations'], {'String': Object});
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
      }
      if (data.hasOwnProperty('updated_at')) {
        obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
      }
    }
    return obj;
  }

  /**
   * Unique Trigger identifier.
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Unique name for this trigger, used to identify this trigger.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Class of trigger, e.g. schedule, http, queue
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * URI path for this trigger. e.g. `sayHello`, `say/hello`
   * @member {String} source
   */
  exports.prototype['source'] = undefined;
  /**
   * Opaque, unique Function identifier
   * @member {String} fn_id
   */
  exports.prototype['fn_id'] = undefined;
  /**
   * Opaque, unique Application identifier
   * @member {String} app_id
   */
  exports.prototype['app_id'] = undefined;
  /**
   * Trigger annotations - this is a map of annotations attached to this trigger, keys must not exceed 128 bytes and must consist of non-whitespace printable ascii characters, and the seralized representation of individual values must not exeed 512 bytes.
   * @member {Object.<String, Object>} annotations
   */
  exports.prototype['annotations'] = undefined;
  /**
   * Time when trigger was created. Always in UTC.
   * @member {Date} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * Most recent time that trigger was updated. Always in UTC.
   * @member {Date} updated_at
   */
  exports.prototype['updated_at'] = undefined;



  return exports;
}));


